### PR TITLE
Website rework.

### PR DESCRIPTION
**Pull request by IMB11**
The website could do with some significant rework. 

Loader name has been left [Insert Name Here] incase you ever plan to rename the loader. (Which I recommend)

image

### CODE REVIEW

**Comment by IMB11** [comment]
image
image
image
image

**Comment by hYdos** [comment]
Is there a chance to get like blog/news posts/updates in there somewhere?

**Comment by IMB11** [comment]
Yes, but that'll require a backend.

**Comment by IMB11** [comment]
I was thinking of putting the blog on the home page.

**Comment by hYdos** [comment]
> Yes, but that'll require a backend.

you can put placeholder text like last time and yea the homepage sounds good.

**Comment by IMB11** [comment]
Kk, I'll do that now

**Comment by IMB11** [comment]
Voilà

**Comment by hYdos** [comment]
screenshots?

**Comment by IMB11** [comment]
I edited on mobile lol, one second I'll try

**Comment by IMB11** [comment]
Screenshot_20220723-123026_Chrome

**Review by hYdos — APPROVED** [review]

**Pull request merged**
